### ISSUE TITLE
the app is crashing on Pixel 2    (API 24)

### ISSUE THREAD

**Issue by andresserranodev** [andresserranodev/Yelp_AAC#17]
2019-11-21 09:12:33.474 9638-9638/com.puzzlebench.yelp_aac D/AndroidRuntime: Shutting down VM

2019-11-21 09:12:33.478 9638-9638/com.puzzlebench.yelp_aac E/AndroidRuntime: FATAL EXCEPTION: main

    Process: com.puzzlebench.yelp_aac, PID: 9638

    java.lang.RuntimeException: Canvas: trying to draw too large(226886436bytes) bitmap.

        at android.view.DisplayListCanvas.throwIfCannotDraw(DisplayListCanvas.java:260)

        at android.graphics.Canvas.drawBitmap(Canvas.java:1415)

        at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:545)

        at android.widget.ImageView.onDraw(ImageView.java:1286)

        at android.view.View.draw(View.java:17071)

        at android.view.View.updateDisplayListIfDirty(View.java:16053)

        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3748)

        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3728)

        at android.view.View.updateDisplayListIfDirty(View.java:16016)

        at android.view.View.draw(View.java:16837)

        at android.view.ViewGroup.drawChild(ViewGroup.java:3764)

        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)

        at android.view.View.updateDisplayListIfDirty(View.java:16048)

        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3748)

        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3728)

        at android.view.View.updateDisplayListIfDirty(View.java:16016)

        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3748)

        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3728)

        at android.view.View.updateDisplayListIfDirty(View.java:16016)

        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3748)

        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3728)

        at android.view.View.updateDisplayListIfDirty(View.java:16016)

        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3748)

        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3728)

        at android.view.View.updateDisplayListIfDirty(View.java:16016)

        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3748)

        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3728)

        at android.view.View.updateDisplayListIfDirty(View.java:16016)

        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3748)

        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3728)

        at android.view.View.updateDisplayListIfDirty(View.java:16016)

        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:656)

        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:662)

        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:770)

        at android.view.ViewRootImpl.draw(ViewRootImpl.java:2796)

        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2604)

        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2211)

        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1246)

        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6301)

        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:871)

        at android.view.Choreographer.doCallbacks(Choreographer.java:683)

        at android.view.Choreographer.doFrame(Choreographer.java:619)

        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857)

        at android.os.Handler.handleCallback(Handler.java:751)

        at android.os.Handler.dispatchMessage(Handler.java:95)

        at android.os.Looper.loop(Looper.java:154)

        at android.app.ActivityThread.main(ActivityThread.java:6077)

        at java.lang.reflect.Method.invoke(Native Method)

        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)

        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)

2019-11-21 09:12:33.482 1629-1728/? W/ActivityManager:   Force finishing activity com.puzzlebench.yelp_aac/.presentation.android.MainActivity

=====================================================

**Comment by adsf117** [comment]
merged on PR https://github.com/adsf117/Yelp_AAC/pull/18

**Comment by andresserranodev** [comment]
fixed on PR https://github.com/adsf117/Yelp_AAC/pull/18
